name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 54.210.31.226  
          username: ubuntu                            
          key: |
            -----BEGIN OPENSSH PRIVATE KEY-----
            b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAACFwAAAAdzc2gtcn
            NhAAAAAwEAAQAAAgEA2Z6QhJatrViM6sjgfkbait+/eta6bfG9Z8CfJeTpyOiC8Pha/quA
            a4Fasg8b2JLTznxNZ8vjocwRB9kjejcHUugwoMiqGu68Tzd7vZetGwDnj8m2Eu7qIB9rm7
            nJ4Qwf/9lTnaYv9+UQhrGiyI36CfyA6mT0f4WbT9kzchLW2/Q0tK1JRxnZlRzHvj5gUcQq
            CuvnETOWh2oh6nB+mIwDfaFyMjs6EoZH4Jdt4scq+KlOzHjXhkizL+Iu9A8YL2kxlpN/Z+
            +A0IWqMBpHeNm1b5r9antVDDwv6KFDXV0Q/bCxxOP4cwt9WX/p2Endau6kwC0NP5fLLVAI
            UbC3eE5XtUbV69LyjwFWJkgfscisHXqmxYvNDFal15bBRIh7EqIAKffimjAjIQnQn5e3v6
            3/cOF5cNXXgDkV0jVHYfflS6JCijSZLWWvyRQ2/HNqagH5nMyW5HYtwPscCo7uBxgsTHOq
            m0+vcuuJL/hrvDzevlzfp1tFBTHfSWTBCvfi0FVbeT4H7ZQfAmvkVb2pqWHLqwmoQGXk4S
            X75R+Es6Sr40XuGXukJE4ZxosF93T30ZPIA/fhJGjHEXOfbKE1RiYOoH/n2CBjCK0txCiB
            l/YyqIPzcpuKbrd1AInXxVl93Stn46+77GEn1z96jGpkKE7Or08v1aTDA5pgpg793Fj/eq
            cAAAdQBYlRqwWJUasAAAAHc3NoLXJzYQAAAgEA2Z6QhJatrViM6sjgfkbait+/eta6bfG9
            Z8CfJeTpyOiC8Pha/quAa4Fasg8b2JLTznxNZ8vjocwRB9kjejcHUugwoMiqGu68Tzd7vZ
            etGwDnj8m2Eu7qIB9rm7nJ4Qwf/9lTnaYv9+UQhrGiyI36CfyA6mT0f4WbT9kzchLW2/Q0
            tK1JRxnZlRzHvj5gUcQqCuvnETOWh2oh6nB+mIwDfaFyMjs6EoZH4Jdt4scq+KlOzHjXhk
            izL+Iu9A8YL2kxlpN/Z++A0IWqMBpHeNm1b5r9antVDDwv6KFDXV0Q/bCxxOP4cwt9WX/p
            2Endau6kwC0NP5fLLVAIUbC3eE5XtUbV69LyjwFWJkgfscisHXqmxYvNDFal15bBRIh7Eq
            IAKffimjAjIQnQn5e3v63/cOF5cNXXgDkV0jVHYfflS6JCijSZLWWvyRQ2/HNqagH5nMyW
            5HYtwPscCo7uBxgsTHOqm0+vcuuJL/hrvDzevlzfp1tFBTHfSWTBCvfi0FVbeT4H7ZQfAm
            vkVb2pqWHLqwmoQGXk4SX75R+Es6Sr40XuGXukJE4ZxosF93T30ZPIA/fhJGjHEXOfbKE1
            RiYOoH/n2CBjCK0txCiBl/YyqIPzcpuKbrd1AInXxVl93Stn46+77GEn1z96jGpkKE7Or0
            8v1aTDA5pgpg793Fj/eqcAAAADAQABAAACAAfr0yPYXjsEkaCMLku6ZYMPkOc2QLP2zCem
            JcTZ176l4/pEd/90G6kOHNCFZ0STV51Y/fJMxBzkEiygdT+iGCSm6fo4Q6TWUslpYhotFr
            J4bnVX6MY4pxIDQsX41cXYzKNh9D61SWKzFk5o0d2N+W96nvCpOxMXOGeIJuy8jdCUy4RW
            GGg7oyVf1k9w8s2XH9ak7pS8NXr5XIGtlZYU5p2gjkkQydTZyWz95hSOnlxNwV4E+gdbxx
            XznDTrBbzYDeOGu+j7GUu9ycuVcUuPVSDaWeYR1i8rU60ajZqs5Azv7RCXIbiCTw4+bzMd
            wS7+v8V0/ln1uwILuznJ/mulImEYHVyvf2YYB/R2bdAZG5boBTbxWlhBpRXi1CB/GjgR1g
            r+XM/xmVWuCcLCUVDtPwU57bOWlvA57Y8zmfP+uVF3RDSK3Ezkbv5RiVuzjizm7jvEiBdy
            4XjKMpCCb+N3Baco/2mKvUM2AANOLcvk5yAEfx6K3lLZDexhlIE+Iyftiql4Ja+u0IBkV/
            bOYmsgiISZWYelFiAEisP7uyEys8VquJ2pYS7lL6ScWQZVm8YqBAMDdfnTuqp4MGENTBEo
            /kCznLYNVWeZ0QRYfmXBTx/ll51zews4VQzcQja6EtcZnrrzFvRkECj8b+OQ/vIpgCgzCB
            /vPjAgXctwh1WfOhdJAAABABf5jRB3kmsmB0MHqU0PBxAk1XneM5iRHoeNxgsSHafK6+aQ
            DSMmxvJoioQ5lI8T+ZlNzDBmlkHp+gCb7ob4Q6wzSxzWrNwkZvvW6CdzjVoGpWMevPB5HU
            0E4efbcAzZsmwDCmLn4hHD1OElvqFk+kmqVrCGBfJdw5hJiyt55BEwDcA4g/JAhQUtAUN1
            Ee7qJErdZE3RZdwpNE02gU1U9Jd0ApS45pgEf2ei00++Z9vPrmv7TCH+PEOL9PcNWszu7S
            nUaFJZL2omEIb22is65rUHZcCRUSJfdKe67NFqVC8JxLcZuRRYkHEr3A8cAPGY5Fdv7chs
            1a3JxUbr4w5qGpkAAAEBAPj6sZ3DrPXOPSVtBriXbHK3VrRsqD+/oDDgdoxjEJkvDHSnqh
            SsUGx/xMMC/pfyrlWS1kf2Gy+ppQd+pajUDZV34lCo0xf+57c6faDmWZU6pfHugK658BKM
            8ANywdy2q20K8q2ofG0R1C/zgx5l4hXMyQau6r0jGNC7CN6qZEYY8TK+Nx0Tw8mTdIkhF/
            7jBpANKBqOjYAdU03lm0PHZjlILKzLhUAaGat50k3sDRbVHl7OXVpm/nuBIiA4UryfMOVM
            uoDzvXOghRSR4HUY2jfKb02+gjbUEvlgVEbV/mxLlF6NiBaQn1aehqC69hw+bmT4mUtcEs
            WseJVI/3jdDE8AAAEBAN/BfkKyHpQHxvfZg2seFIAPvR7RRk+GYXmD8TaOrg30tV+fWhck
            Qn1J5q5HezelJnZWlc0WDW2thHZdu25sYtmVgHHu+/LOr9WJKO0JMWmsRSpobp7zEsgcoU
            dY8K14E+P0AQtTADtDVOTzabYbLtfvLpp2edGIlAFWB9MZ1JAwcpoADykqxevXmP+aYYdv
            GBFIJBYiNtDfUW4g2MI7BneVhLaAl+6onGa/9W/LPfAGeo3cLU4swZYaL+yqe9tAknExEi
            KhyuftD7J333T8s42Dh0qGJcSw5bJ6O8KXbqkFmvCbo/seUp7hEOg+j8guF6+Ih85PBgUO
            xbiCkc1U3ikAAAAVcm9vdEBpcC0xNzItMzEtODEtMTAzAQIDBAUG
            -----END OPENSSH PRIVATE KEY-----
          port: 22
          script: |
            cd "/home/ubuntu/.ssh/github-deploy.pub"
            echo "Stopping existing container if running..."
            docker stop gitinfo-app || true
            docker rm gitinfo-app || true
            
            echo "Freeing port 5000 if used..."
            CONTAINER_ID=$(docker ps -q --filter "publish=5000")
            if [ -n "$CONTAINER_ID" ]; then
              echo "Stopping container using port 5000: $CONTAINER_ID"
              docker stop $CONTAINER_ID || true
              docker rm $CONTAINER_ID || true
            fi
            
            echo "Building new Docker image..."
            docker build -t gitinfo-app .
            
            echo "Running new container..."
            docker run -d -p 5000:5000 --name gitinfo-app gitinfo-app
